CREATE TABLE IF NOT EXISTS class_session_reschedule_proposals (
    reschedule_proposal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_session_id INTEGER NOT NULL,
    proposed_by_user_id VARCHAR(50) NOT NULL,
    proposed_by_role VARCHAR(20) NOT NULL,
    counterpart_user_id VARCHAR(50) NOT NULL,
    counterpart_role VARCHAR(20) NOT NULL,
    original_scheduled_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    original_scheduled_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    proposed_scheduled_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    proposed_scheduled_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reason VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    responded_at TIMESTAMP WITHOUT TIME ZONE,
    responded_by VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT class_session_reschedule_proposals_session_fkey
        FOREIGN KEY (class_session_id)
        REFERENCES class_sessions (class_session_id)
        ON DELETE CASCADE,
    CONSTRAINT class_session_reschedule_proposals_status_check
        CHECK (status IN ('pending', 'accepted', 'rejected', 'expired')),
    CONSTRAINT class_session_reschedule_proposals_proposed_by_role_check
        CHECK (proposed_by_role IN ('Tutor', 'Student', 'Parent')),
    CONSTRAINT class_session_reschedule_proposals_counterpart_role_check
        CHECK (counterpart_role IN ('Tutor', 'Student', 'Parent'))
);

CREATE INDEX IF NOT EXISTS idx_reschedule_proposals_session
    ON class_session_reschedule_proposals (class_session_id);

CREATE INDEX IF NOT EXISTS idx_reschedule_proposals_active
    ON class_session_reschedule_proposals (class_session_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS ux_reschedule_proposals_one_pending
    ON class_session_reschedule_proposals (class_session_id)
    WHERE status = 'pending';
