CREATE TABLE IF NOT EXISTS class_session_schedule_changes (
    schedule_change_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_session_id INTEGER NOT NULL,
    original_scheduled_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    original_scheduled_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    tutor_user_id VARCHAR(50) NOT NULL,
    learner_approver_user_id VARCHAR(50) NOT NULL,
    learner_approver_role VARCHAR(20) NOT NULL,
    tutor_confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    tutor_confirmed_by VARCHAR(50),
    learner_confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    learner_confirmed_by VARCHAR(50),
    rejected_at TIMESTAMP WITHOUT TIME ZONE,
    rejected_by VARCHAR(50),
    requested_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    approved_at TIMESTAMP WITHOUT TIME ZONE,
    applied_at TIMESTAMP WITHOUT TIME ZONE,
    adjusted_scheduled_start TIMESTAMP WITHOUT TIME ZONE,
    adjusted_scheduled_end TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT class_session_schedule_changes_session_fkey
        FOREIGN KEY (class_session_id)
        REFERENCES class_sessions (class_session_id)
        ON DELETE CASCADE,
    CONSTRAINT class_session_schedule_changes_status_check
        CHECK (status IN ('pending', 'approved', 'applied', 'rejected', 'expired')),
    CONSTRAINT class_session_schedule_changes_approver_role_check
        CHECK (learner_approver_role IN ('Student', 'Parent'))
);

CREATE INDEX IF NOT EXISTS idx_schedule_changes_session
    ON class_session_schedule_changes (class_session_id);

CREATE INDEX IF NOT EXISTS idx_schedule_changes_active
    ON class_session_schedule_changes (class_session_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_changes_one_active
    ON class_session_schedule_changes (class_session_id)
    WHERE status IN ('pending', 'approved');
