-- Expand payment persistence so PayOS link/request data and actual bank
-- transactions have separate ownership. Booking PayOS columns are intentionally
-- retained in this release as a rollback/backfill source; application code no
-- longer writes them.

BEGIN;

CREATE TABLE IF NOT EXISTS public.payment_requests (
    payment_request_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id               INTEGER NOT NULL,
    user_id                  VARCHAR(50),
    provider                 VARCHAR(20) NOT NULL DEFAULT 'PayOS',
    phase                    VARCHAR(20) NOT NULL,
    order_code               BIGINT,
    payment_link_id          VARCHAR(255),
    amount                   NUMERIC(15, 2),
    currency                 VARCHAR(10) NOT NULL DEFAULT 'VND',
    status                   VARCHAR(30) NOT NULL,
    destination_bank_bin     VARCHAR(20),
    destination_bank_name    VARCHAR(100),
    display_account_number   VARCHAR(50),
    display_account_name     VARCHAR(200),
    description              TEXT,
    checkout_url             TEXT,
    qr_code                  TEXT,
    expires_at               TIMESTAMP WITHOUT TIME ZONE,
    provider_payload         JSONB,
    legacy_reconciliation_version VARCHAR(30),
    created_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_requests_booking_id_fkey
        FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id) ON DELETE RESTRICT,
    CONSTRAINT payment_requests_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL,
    CONSTRAINT ck_payment_requests_phase
        CHECK (phase IN ('deposit', 'remaining', 'legacy_unknown')),
    CONSTRAINT ck_payment_requests_status
        CHECK (status IN (
            'PENDING', 'PROCESSING', 'PAID', 'CANCELLED',
            'EXPIRED', 'SUPERSEDED', 'REQUIRES_REVIEW', 'UNKNOWN'
        )),
    CONSTRAINT ck_payment_requests_amount
        CHECK (amount IS NULL OR amount > 0)
);

ALTER TABLE public.payment_requests
    ADD COLUMN IF NOT EXISTS legacy_reconciliation_version VARCHAR(30);

-- Snapshot only rows that existed when this migration first ran. The temporary
-- DEFAULT backfills existing rows, then is removed so rows created by the
-- application after deployment remain unmarked on any direct SQL rerun.
ALTER TABLE public.bookings
    ADD COLUMN IF NOT EXISTS payos_legacy_reconciliation_version VARCHAR(30)
        DEFAULT 'V20260716';

ALTER TABLE public.bookings
    ALTER COLUMN payos_legacy_reconciliation_version DROP DEFAULT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_requests_provider_link
    ON public.payment_requests(provider, payment_link_id)
    WHERE payment_link_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_requests_provider_order
    ON public.payment_requests(provider, order_code)
    WHERE order_code IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_requests_active_booking_phase
    ON public.payment_requests(booking_id, phase)
    WHERE phase IN ('deposit', 'remaining')
      AND status IN ('PENDING', 'PROCESSING', 'REQUIRES_REVIEW', 'UNKNOWN');

CREATE INDEX IF NOT EXISTS idx_payment_requests_booking_created
    ON public.payment_requests(booking_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_requests_user
    ON public.payment_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_requests_status
    ON public.payment_requests(status);

ALTER TABLE public.payment_transactions
    ADD COLUMN IF NOT EXISTS payment_request_id INTEGER,
    ADD COLUMN IF NOT EXISTS capture_source VARCHAR(20) NOT NULL DEFAULT 'Legacy',
    ADD COLUMN IF NOT EXISTS reconciliation_status VARCHAR(30) NOT NULL DEFAULT 'Matched',
    ADD COLUMN IF NOT EXISTS capture_fingerprint VARCHAR(64),
    ADD COLUMN IF NOT EXISTS destination_virtual_account_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS destination_virtual_account_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS webhook_payload TEXT,
    ADD COLUMN IF NOT EXISTS legacy_reconciliation_version VARCHAR(30)
        DEFAULT 'V20260716';

ALTER TABLE public.payment_transactions
    ALTER COLUMN legacy_reconciliation_version DROP DEFAULT;

-- New signed webhook bodies retain their exact raw representation. Historical
-- JSONB values can only be converted to normalized JSON text; original spacing
-- and byte representation cannot be recovered retroactively.
ALTER TABLE public.payment_transactions
    ALTER COLUMN webhook_payload TYPE TEXT
    USING webhook_payload::TEXT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'payment_transactions'
          AND column_name = 'destination_account_bank_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'payment_transactions'
          AND column_name = 'destination_account_bank_bin'
    ) THEN
        ALTER TABLE public.payment_transactions
            RENAME COLUMN destination_account_bank_id TO destination_account_bank_bin;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'payment_transactions_payment_request_id_fkey'
    ) THEN
        ALTER TABLE public.payment_transactions
            ADD CONSTRAINT payment_transactions_payment_request_id_fkey
            FOREIGN KEY (payment_request_id)
            REFERENCES public.payment_requests(payment_request_id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_payment_transactions_payment_request
    ON public.payment_transactions(payment_request_id);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.payment_transactions
        WHERE withdrawal_id IS NOT NULL
          AND purpose = 'Withdrawal'
          AND status = 'Succeeded'
        GROUP BY withdrawal_id
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION
            'Duplicate successful payout transactions exist for one or more withdrawals';
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_transactions_withdrawal_payout
    ON public.payment_transactions(withdrawal_id)
    WHERE withdrawal_id IS NOT NULL
      AND purpose = 'Withdrawal'
      AND status = 'Succeeded';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.payment_transactions
        WHERE channel = 'Manual'
          AND legacy_reconciliation_version = 'V20260716'
          AND provider_transaction_id IS NOT NULL
        GROUP BY upper(provider_transaction_id)
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION
            'Case-insensitive duplicate manual transaction references exist';
    END IF;
END $$;

UPDATE public.payment_transactions
SET provider_transaction_id = upper(provider_transaction_id)
WHERE channel = 'Manual'
  AND legacy_reconciliation_version = 'V20260716'
  AND provider_transaction_id IS NOT NULL;

-- Multiple real bank transfers may contribute to one payment request.
DROP INDEX IF EXISTS public.uq_payment_transactions_matched_request;

-- Recover one request for every distinct PayOS booking transaction before using
-- the single legacy booking cache as a fallback. A booking may have both a
-- deposit link and a remaining-payment link, while bookings only retained the
-- most recently generated link.
WITH raw_transaction_evidence AS (
    SELECT
        pt.payment_transaction_id,
        pt.booking_id,
        COALESCE(pt.user_id, b.parent_id) AS user_id,
        pt.purpose,
        pt.amount,
        pt.currency,
        pt.description,
        pt.destination_account_bank_bin,
        pt.destination_account_bank_name,
        pt.order_code AS stored_order_code,
        pt.created_at,
        pt.paid_at,
        pt.provider_payload AS raw_provider_payload,
        b.payment_code AS cached_payment_link_id,
        b.payos_bin,
        b.payos_account_number,
        b.payos_account_name,
        b.payos_description,
        b.payos_checkout_url,
        b.payos_qr_code,
        b.payment_due_at,
        b.deposit_amount,
        b.remaining_amount,
        b.final_price,
        NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,orderCode}',
            pt.provider_payload ->> 'orderCode'
        )), '') AS payload_order_code,
        CASE
            WHEN jsonb_typeof(pt.provider_payload -> 'transactions') = 'array'
                THEN NULLIF(BTRIM(
                    pt.provider_payload ->> 'amount'
                ), '')
        END AS provider_request_amount,
        NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,paymentLinkId}',
            pt.provider_payload ->> 'id',
            pt.payment_link_id
        )), '') AS recovered_payment_link_id
    FROM public.payment_transactions pt
    JOIN public.bookings b ON b.booking_id = pt.booking_id
    WHERE pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
      AND pt.status = 'Succeeded'
      AND pt.booking_id IS NOT NULL
      AND pt.purpose IN ('BookingDeposit', 'BookingRemaining')
), transaction_evidence AS (
    SELECT
        r.*,
        CASE
            WHEN r.payload_order_code ~ '^[0-9]{1,18}$'
                THEN r.payload_order_code::BIGINT
            ELSE r.stored_order_code
        END AS recovered_order_code,
        CASE
            WHEN r.provider_request_amount ~
                '^[0-9]{1,13}([.][0-9]{1,2})?$'
                THEN r.provider_request_amount::NUMERIC(15, 2)
            ELSE NULL
        END AS recovered_provider_request_amount
    FROM raw_transaction_evidence r
), normalized_transaction_evidence AS (
    SELECT
        e.*,
        CASE
            WHEN e.purpose = 'BookingDeposit' THEN 'deposit'
            WHEN e.purpose = 'BookingRemaining' THEN 'remaining'
            WHEN e.recovered_order_code / 100000000000 = 1
                THEN 'deposit'
            WHEN e.recovered_order_code / 100000000000 = 2
                THEN 'remaining'
            ELSE 'legacy_unknown'
        END AS phase
    FROM transaction_evidence e
), request_transaction_evidence AS (
    SELECT
        e.*,
        CASE
            WHEN e.phase = 'deposit' THEN COALESCE(
                CASE
                    WHEN e.deposit_amount > 0 THEN e.deposit_amount
                END,
                e.recovered_provider_request_amount
            )
            WHEN e.phase = 'remaining' THEN COALESCE(
                CASE
                    WHEN e.remaining_amount > 0 THEN e.remaining_amount
                END,
                e.recovered_provider_request_amount
            )
            ELSE COALESCE(
                CASE
                    WHEN e.final_price > 0 THEN e.final_price
                END,
                e.recovered_provider_request_amount
            )
        END AS raw_expected_amount
    FROM normalized_transaction_evidence e
)
INSERT INTO public.payment_requests (
    booking_id,
    user_id,
    provider,
    phase,
    order_code,
    payment_link_id,
    amount,
    currency,
    status,
    destination_bank_bin,
    destination_bank_name,
    display_account_number,
    display_account_name,
    description,
    checkout_url,
    qr_code,
    expires_at,
    provider_payload,
    created_at,
    updated_at
)
SELECT
    e.booking_id,
    e.user_id,
    'PayOS',
    e.phase,
    e.recovered_order_code,
    e.recovered_payment_link_id,
    CASE
        WHEN e.raw_expected_amount > 0 THEN e.raw_expected_amount
        ELSE NULL
    END,
    COALESCE(NULLIF(e.currency, ''), 'VND'),
    'PAID',
    COALESCE(
        e.destination_account_bank_bin,
        CASE
            WHEN e.cached_payment_link_id = e.recovered_payment_link_id
                THEN e.payos_bin
        END
    ),
    e.destination_account_bank_name,
    CASE
        WHEN e.cached_payment_link_id = e.recovered_payment_link_id
            THEN e.payos_account_number
    END,
    CASE
        WHEN e.cached_payment_link_id = e.recovered_payment_link_id
            THEN e.payos_account_name
    END,
    COALESCE(
        CASE
            WHEN e.cached_payment_link_id = e.recovered_payment_link_id
                THEN e.payos_description
        END,
        e.description
    ),
    CASE
        WHEN e.cached_payment_link_id = e.recovered_payment_link_id
            THEN e.payos_checkout_url
    END,
    CASE
        WHEN e.cached_payment_link_id = e.recovered_payment_link_id
            THEN e.payos_qr_code
    END,
    CASE
        WHEN e.cached_payment_link_id = e.recovered_payment_link_id
            THEN e.payment_due_at
    END,
    (
        CASE
            WHEN jsonb_typeof(e.raw_provider_payload) = 'object'
                THEN e.raw_provider_payload
            ELSE jsonb_build_object(
                'legacyPayload',
                e.raw_provider_payload
            )
        END
        || jsonb_build_object(
            '_source', 'legacy_payment_transaction',
            'paymentTransactionId', e.payment_transaction_id,
            'orderCode', e.recovered_order_code,
            'paymentLinkId', e.recovered_payment_link_id
        )
    ),
    COALESCE(e.created_at, e.paid_at, CURRENT_TIMESTAMP),
    COALESCE(e.paid_at, e.created_at, CURRENT_TIMESTAMP)
FROM request_transaction_evidence e
WHERE e.recovered_payment_link_id IS NOT NULL
   OR e.recovered_order_code IS NOT NULL
ON CONFLICT DO NOTHING;

-- Historical polling stored one payment-link row using the request total and
-- only copied fields from transactions[last]. Expand a trustworthy array into
-- one ledger row per real bank transfer before normalizing/attaching rows.
-- Missing/duplicate references, invalid amounts/timestamps, or references that
-- already belong to another ledger row are not guessed: the related request is
-- forced to review instead of being allowed to reconcile as Matched.
CREATE TEMP TABLE legacy_payos_transaction_expansion
ON COMMIT DROP
AS
WITH array_elements AS (
    SELECT
        pt.payment_transaction_id AS source_payment_transaction_id,
        pt.provider_transaction_id AS existing_reference,
        pt.order_code AS stored_order_code,
        pt.payment_link_id AS stored_payment_link_id,
        pt.provider_payload AS root_provider_payload,
        element.value AS element_payload,
        element.ordinality::INTEGER AS element_ordinal
    FROM public.payment_transactions pt
    CROSS JOIN LATERAL jsonb_array_elements(
        pt.provider_payload -> 'transactions'
    ) WITH ORDINALITY AS element(value, ordinality)
    WHERE pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
      AND pt.status = 'Succeeded'
      AND pt.booking_id IS NOT NULL
      AND pt.purpose IN ('BookingDeposit', 'BookingRemaining')
      AND jsonb_typeof(pt.provider_payload -> 'transactions') = 'array'
), extracted_elements AS (
    SELECT
        e.*,
        NULLIF(NULLIF(BTRIM(
            e.element_payload ->> 'reference'
        ), ''), '0') AS element_reference,
        NULLIF(BTRIM(
            e.element_payload ->> 'amount'
        ), '') AS element_amount_text,
        NULLIF(BTRIM(
            e.element_payload ->> 'transactionDateTime'
        ), '') AS element_transaction_datetime,
        CASE
            WHEN NULLIF(BTRIM(COALESCE(
                e.root_provider_payload #>> '{data,orderCode}',
                e.root_provider_payload ->> 'orderCode'
            )), '') ~ '^[0-9]{1,18}$'
                THEN NULLIF(BTRIM(COALESCE(
                    e.root_provider_payload #>> '{data,orderCode}',
                    e.root_provider_payload ->> 'orderCode'
                )), '')::BIGINT
            ELSE e.stored_order_code
        END AS recovered_order_code,
        COALESCE(
            NULLIF(BTRIM(
                e.root_provider_payload #>> '{data,paymentLinkId}'
            ), ''),
            NULLIF(BTRIM(
                e.root_provider_payload ->> 'id'
            ), ''),
            NULLIF(BTRIM(e.stored_payment_link_id), '')
        ) AS recovered_payment_link_id
    FROM array_elements e
), qualified_elements AS (
    SELECT
        e.*,
        jsonb_typeof(e.element_payload) = 'object'
            AS element_is_object,
        CASE
            WHEN e.element_amount_text ~
                '^[0-9]{1,13}([.][0-9]{1,2})?$'
                THEN e.element_amount_text::NUMERIC(15, 2) > 0
            ELSE FALSE
        END AS amount_is_valid,
        CASE
            WHEN e.element_transaction_datetime ~
                '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?(Z|[+-][0-9]{2}:?[0-9]{2})$'
                THEN pg_input_is_valid(
                    e.element_transaction_datetime,
                    'timestamp with time zone'
                )
            WHEN e.element_transaction_datetime ~
                '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?$'
                THEN pg_input_is_valid(
                    replace(
                        e.element_transaction_datetime,
                        'T',
                        ' '
                    ),
                    'timestamp without time zone'
                )
            ELSE FALSE
        END AS timestamp_is_valid,
        COALESCE(char_length(
            e.element_payload ->> 'code'
        ) <= 50, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'counterAccountBankId'
        ) <= 50, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'counterAccountBankName'
        ) <= 100, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'counterAccountNumber'
        ) <= 50, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'counterAccountName'
        ) <= 200, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'accountNumber'
        ) <= 50, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'accountName'
        ) <= 200, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'virtualAccountNumber'
        ) <= 50, TRUE)
        AND COALESCE(char_length(
            e.element_payload ->> 'virtualAccountName'
        ) <= 200, TRUE)
            AS bounded_fields_are_valid,
        EXISTS (
            SELECT 1
            FROM public.payment_transactions other
            WHERE other.payment_transaction_id
                    <> e.source_payment_transaction_id
              AND other.channel = 'PayOS'
              AND NULLIF(BTRIM(
                  other.provider_transaction_id
              ), '') = e.element_reference
        ) AS reference_conflicts
    FROM extracted_elements e
), source_quality AS (
    SELECT
        source_payment_transaction_id,
        BOOL_AND(
            element_is_object
            AND element_reference IS NOT NULL
            AND char_length(element_reference) <= 255
            AND amount_is_valid
            AND timestamp_is_valid
            AND bounded_fields_are_valid
            AND NOT reference_conflicts
        ) AS all_elements_trustworthy,
        COUNT(DISTINCT element_reference) = COUNT(*)
            AS references_are_unique
    FROM qualified_elements
    GROUP BY source_payment_transaction_id
), trustworthy_elements AS (
    SELECT
        e.*,
        CASE
            WHEN e.element_amount_text ~
                '^[0-9]{1,13}([.][0-9]{1,2})?$'
                THEN e.element_amount_text::NUMERIC(15, 2)
        END AS element_amount,
        CASE
            WHEN e.element_transaction_datetime ~
                '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?(Z|[+-][0-9]{2}:?[0-9]{2})$'
                 AND pg_input_is_valid(
                     e.element_transaction_datetime,
                     'timestamp with time zone'
                 )
                THEN e.element_transaction_datetime::TIMESTAMPTZ
                    AT TIME ZONE 'UTC'
            WHEN e.element_transaction_datetime ~
                '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?$'
                 AND pg_input_is_valid(
                     replace(
                         e.element_transaction_datetime,
                         'T',
                         ' '
                     ),
                     'timestamp without time zone'
                 )
                THEN (
                    replace(
                        e.element_transaction_datetime,
                        'T',
                        ' '
                    )::TIMESTAMP
                    AT TIME ZONE 'Asia/Ho_Chi_Minh'
                ) AT TIME ZONE 'UTC'
        END AS element_paid_at
    FROM qualified_elements e
    JOIN source_quality quality
      ON quality.source_payment_transaction_id
            = e.source_payment_transaction_id
    WHERE quality.all_elements_trustworthy
      AND quality.references_are_unique
)
SELECT
    e.*,
    ROW_NUMBER() OVER (
        PARTITION BY e.source_payment_transaction_id
        ORDER BY
            CASE
                WHEN NULLIF(BTRIM(e.existing_reference), '')
                        = e.element_reference
                    THEN 0
                ELSE 1
            END,
            e.element_ordinal DESC
    ) AS anchor_rank
FROM trustworthy_elements e;

-- Any array that did not qualify for expansion is ambiguous. Keep its original
-- evidence intact, but remove the expected amount from its request so the
-- normal aggregate reconciliation below produces Unexpected/RequiresReview.
WITH invalid_array_sources AS (
    SELECT
        pt.payment_transaction_id,
        pt.booking_id,
        pt.purpose,
        CASE
            WHEN NULLIF(BTRIM(COALESCE(
                pt.provider_payload #>> '{data,orderCode}',
                pt.provider_payload ->> 'orderCode'
            )), '') ~ '^[0-9]{1,18}$'
                THEN NULLIF(BTRIM(COALESCE(
                    pt.provider_payload #>> '{data,orderCode}',
                    pt.provider_payload ->> 'orderCode'
                )), '')::BIGINT
            ELSE pt.order_code
        END AS recovered_order_code,
        COALESCE(
            NULLIF(BTRIM(
                pt.provider_payload #>> '{data,paymentLinkId}'
            ), ''),
            NULLIF(BTRIM(
                pt.provider_payload ->> 'id'
            ), ''),
            NULLIF(BTRIM(pt.payment_link_id), '')
        ) AS recovered_payment_link_id
    FROM public.payment_transactions pt
    WHERE pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
      AND pt.status = 'Succeeded'
      AND pt.booking_id IS NOT NULL
      AND pt.purpose IN ('BookingDeposit', 'BookingRemaining')
      AND jsonb_typeof(pt.provider_payload -> 'transactions') = 'array'
      AND NOT EXISTS (
          SELECT 1
          FROM legacy_payos_transaction_expansion expanded
          WHERE expanded.source_payment_transaction_id
                = pt.payment_transaction_id
      )
)
UPDATE public.payment_requests pr
SET
    amount = NULL,
    status = 'REQUIRES_REVIEW',
    provider_payload = COALESCE(
        pr.provider_payload,
        '{}'::JSONB
    ) || jsonb_build_object(
        '_legacyArrayReview',
        'invalid_or_ambiguous_transactions'
    ),
    updated_at = CURRENT_TIMESTAMP
FROM invalid_array_sources invalid
WHERE pr.provider = 'PayOS'
  AND pr.booking_id = invalid.booking_id
  AND (
      (
          invalid.purpose = 'BookingDeposit'
          AND pr.phase IN ('deposit', 'legacy_unknown')
      )
      OR (
          invalid.purpose = 'BookingRemaining'
          AND pr.phase IN ('remaining', 'legacy_unknown')
      )
  )
  AND (
      (
          invalid.recovered_payment_link_id IS NOT NULL
          AND pr.payment_link_id
                = invalid.recovered_payment_link_id
      )
      OR (
          invalid.recovered_order_code IS NOT NULL
          AND pr.order_code = invalid.recovered_order_code
      )
  );

-- Reuse the historical row for the element it already represented (normally
-- transactions[last]); this preserves its primary key for audit references.
UPDATE public.payment_transactions pt
SET
    amount = expanded.element_amount,
    order_code = expanded.recovered_order_code,
    provider_transaction_id = expanded.element_reference,
    payment_link_id = expanded.recovered_payment_link_id,
    description = COALESCE(
        NULLIF(BTRIM(
            expanded.element_payload ->> 'description'
        ), ''),
        pt.description
    ),
    paid_at = expanded.element_paid_at,
    capture_source = 'Polling',
    reconciliation_status = 'Matched',
    capture_fingerprint = NULL,
    provider_code = COALESCE(
        NULLIF(BTRIM(
            expanded.element_payload ->> 'code'
        ), ''),
        pt.provider_code
    ),
    provider_desc = COALESCE(
        NULLIF(BTRIM(
            expanded.element_payload ->> 'desc'
        ), ''),
        pt.provider_desc
    ),
    source_account_bank_id = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountBankId'
    ), ''), '0'),
    source_account_bank_name = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountBankName'
    ), ''), '0'),
    source_account_number = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountNumber'
    ), ''), '0'),
    source_account_name = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountName'
    ), ''), '0'),
    destination_account_number = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'accountNumber'
    ), ''), '0'),
    destination_account_name = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'accountName'
    ), ''), '0'),
    destination_virtual_account_number = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'virtualAccountNumber'
    ), ''), '0'),
    destination_virtual_account_name = NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'virtualAccountName'
    ), ''), '0'),
    provider_payload = expanded.element_payload
FROM legacy_payos_transaction_expansion expanded
WHERE expanded.anchor_rank = 1
  AND pt.payment_transaction_id
        = expanded.source_payment_transaction_id;

-- Insert every other real transfer as an independent immutable ledger row.
INSERT INTO public.payment_transactions (
    user_id,
    channel,
    direction,
    purpose,
    status,
    amount,
    currency,
    order_code,
    provider_transaction_id,
    payment_link_id,
    booking_id,
    withdrawal_id,
    description,
    paid_at,
    created_at,
    processed_by,
    note,
    webhook_code,
    webhook_desc,
    webhook_success,
    provider_code,
    provider_desc,
    source_account_bank_id,
    source_account_bank_name,
    source_account_number,
    source_account_name,
    destination_account_bank_bin,
    destination_account_bank_name,
    destination_account_number,
    destination_account_name,
    provider_payload,
    payment_request_id,
    capture_source,
    reconciliation_status,
    capture_fingerprint,
    destination_virtual_account_number,
    destination_virtual_account_name,
    webhook_payload,
    legacy_reconciliation_version
)
SELECT
    source.user_id,
    source.channel,
    source.direction,
    source.purpose,
    source.status,
    expanded.element_amount,
    source.currency,
    expanded.recovered_order_code,
    expanded.element_reference,
    expanded.recovered_payment_link_id,
    source.booking_id,
    source.withdrawal_id,
    COALESCE(
        NULLIF(BTRIM(
            expanded.element_payload ->> 'description'
        ), ''),
        source.description
    ),
    expanded.element_paid_at,
    source.created_at,
    source.processed_by,
    source.note,
    source.webhook_code,
    source.webhook_desc,
    source.webhook_success,
    COALESCE(
        NULLIF(BTRIM(
            expanded.element_payload ->> 'code'
        ), ''),
        source.provider_code
    ),
    COALESCE(
        NULLIF(BTRIM(
            expanded.element_payload ->> 'desc'
        ), ''),
        source.provider_desc
    ),
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountBankId'
    ), ''), '0'),
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountBankName'
    ), ''), '0'),
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountNumber'
    ), ''), '0'),
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'counterAccountName'
    ), ''), '0'),
    source.destination_account_bank_bin,
    source.destination_account_bank_name,
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'accountNumber'
    ), ''), '0'),
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'accountName'
    ), ''), '0'),
    expanded.element_payload,
    source.payment_request_id,
    'Polling',
    'Matched',
    NULL,
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'virtualAccountNumber'
    ), ''), '0'),
    NULLIF(NULLIF(BTRIM(
        expanded.element_payload ->> 'virtualAccountName'
    ), ''), '0'),
    source.webhook_payload,
    source.legacy_reconciliation_version
FROM legacy_payos_transaction_expansion expanded
JOIN public.payment_transactions source
  ON source.payment_transaction_id
        = expanded.source_payment_transaction_id
WHERE expanded.anchor_rank > 1
ON CONFLICT DO NOTHING;

-- Recover legacy booking link snapshots before application code stops mapping
-- the source columns. Provider orderCode always wins over the old transaction
-- column because older polling code generated a fresh random order code.
WITH legacy_links AS (
    SELECT
        b.booking_id,
        b.parent_id AS user_id,
        b.payment_code AS payment_link_id,
        CASE
            WHEN tx.purpose = 'BookingDeposit' THEN 'deposit'
            WHEN tx.purpose = 'BookingRemaining' THEN 'remaining'
            WHEN lower(COALESCE(b.payos_description, '')) LIKE '%tra not booking%' THEN 'remaining'
            WHEN lower(COALESCE(b.payos_description, '')) LIKE '%coc booking%' THEN 'deposit'
            WHEN b.deposit_paid_at IS NULL THEN 'deposit'
            WHEN b.remaining_paid_at IS NULL THEN 'remaining'
            ELSE 'legacy_unknown'
        END AS phase,
        CASE
            WHEN COALESCE(
                tx.provider_payload ->> 'orderCode',
                tx.provider_payload #>> '{data,orderCode}'
            ) ~ '^[0-9]{1,18}$'
            THEN COALESCE(
                tx.provider_payload ->> 'orderCode',
                tx.provider_payload #>> '{data,orderCode}'
            )::BIGINT
            ELSE tx.order_code
        END AS recovered_order_code,
        b.deposit_amount,
        b.remaining_amount,
        b.final_price,
        b.currency,
        b.payos_bin,
        b.payos_account_number,
        b.payos_account_name,
        b.payos_description,
        b.payos_checkout_url,
        b.payos_qr_code,
        b.payment_due_at,
        b.created_at,
        b.updated_at,
        b.deposit_paid_at,
        b.remaining_paid_at
    FROM public.bookings b
    LEFT JOIN LATERAL (
        SELECT pt.*
        FROM public.payment_transactions pt
        WHERE pt.booking_id = b.booking_id
          AND pt.channel = 'PayOS'
        ORDER BY
            CASE WHEN pt.payment_link_id = b.payment_code THEN 0 ELSE 1 END,
            pt.created_at DESC,
            pt.payment_transaction_id DESC
        LIMIT 1
    ) tx ON TRUE
    WHERE b.payment_code IS NOT NULL
      AND b.payos_legacy_reconciliation_version = 'V20260716'
      AND NOT EXISTS (
          SELECT 1
          FROM public.payment_requests existing_request
          WHERE existing_request.provider = 'PayOS'
            AND existing_request.payment_link_id = b.payment_code
      )
), normalized_legacy_links AS (
    SELECT
        l.*,
        CASE
            WHEN l.phase = 'deposit' THEN l.deposit_amount
            WHEN l.phase = 'remaining' THEN l.remaining_amount
            ELSE l.final_price
        END AS raw_expected_amount
    FROM legacy_links l
)
INSERT INTO public.payment_requests (
    booking_id,
    user_id,
    provider,
    phase,
    order_code,
    payment_link_id,
    amount,
    currency,
    status,
    destination_bank_bin,
    display_account_number,
    display_account_name,
    description,
    checkout_url,
    qr_code,
    expires_at,
    provider_payload,
    created_at,
    updated_at
)
SELECT
    l.booking_id,
    l.user_id,
    'PayOS',
    l.phase,
    l.recovered_order_code,
    l.payment_link_id,
    CASE
        WHEN l.raw_expected_amount > 0 THEN l.raw_expected_amount
        ELSE NULL
    END,
    COALESCE(NULLIF(l.currency, ''), 'VND'),
    CASE
        WHEN l.phase = 'deposit' AND l.deposit_paid_at IS NOT NULL THEN 'PAID'
        WHEN l.phase = 'remaining' AND l.remaining_paid_at IS NOT NULL THEN 'PAID'
        ELSE 'UNKNOWN'
    END,
    l.payos_bin,
    l.payos_account_number,
    l.payos_account_name,
    l.payos_description,
    l.payos_checkout_url,
    l.payos_qr_code,
    l.payment_due_at,
    jsonb_build_object(
        '_source', 'bookings_legacy_cache',
        'paymentLinkId', l.payment_link_id,
        'bin', l.payos_bin,
        'accountNumber', l.payos_account_number,
        'accountName', l.payos_account_name,
        'description', l.payos_description,
        'checkoutUrl', l.payos_checkout_url,
        'qrCode', l.payos_qr_code
    ),
    COALESCE(l.created_at, CURRENT_TIMESTAMP),
    COALESCE(l.updated_at, l.created_at, CURRENT_TIMESTAMP)
FROM normalized_legacy_links l
ON CONFLICT DO NOTHING;

-- A historical polling fallback used payment-link identifiers such as
-- payos-link-... as provider transaction ids. They are not bank references.
UPDATE public.payment_transactions
SET provider_transaction_id = NULL
WHERE channel = 'PayOS'
  AND legacy_reconciliation_version = 'V20260716'
  AND provider_transaction_id ILIKE 'payos-link-%';

-- Normalize and repair parsed transaction fields from provider evidence. Do not
-- synthesize fingerprints here: runtime fingerprints are SHA-256 over a strict
-- canonical representation that legacy SQL data cannot reproduce reliably.
WITH raw_extracted AS (
    SELECT
        pt.payment_transaction_id,
        pt.created_at,
        pt.provider_transaction_id AS existing_reference,
        NULLIF(BTRIM(COALESCE(
            pt.provider_transaction_id,
            pt.provider_payload #>> '{data,reference}',
            pt.provider_payload ->> 'reference'
        )), '') AS actual_reference,
        NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,orderCode}',
            pt.provider_payload ->> 'orderCode'
        )), '') AS payload_order_code,
        NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,paymentLinkId}',
            pt.provider_payload ->> 'id',
            pt.payment_link_id
        )), '') AS recovered_payment_link_id,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,accountNumber}',
            pt.provider_payload ->> 'accountNumber'
        )), ''), '0') AS destination_account_number,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,accountName}',
            pt.provider_payload ->> 'accountName'
        )), ''), '0') AS destination_account_name,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,virtualAccountNumber}',
            pt.provider_payload ->> 'virtualAccountNumber'
        )), ''), '0') AS destination_virtual_account_number,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,virtualAccountName}',
            pt.provider_payload ->> 'virtualAccountName'
        )), ''), '0') AS destination_virtual_account_name,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,counterAccountBankId}',
            pt.provider_payload ->> 'counterAccountBankId'
        )), ''), '0') AS source_account_bank_id,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,counterAccountBankName}',
            pt.provider_payload ->> 'counterAccountBankName'
        )), ''), '0') AS source_account_bank_name,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,counterAccountNumber}',
            pt.provider_payload ->> 'counterAccountNumber'
        )), ''), '0') AS source_account_number,
        NULLIF(NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,counterAccountName}',
            pt.provider_payload ->> 'counterAccountName'
        )), ''), '0') AS source_account_name,
        NULLIF(BTRIM(COALESCE(
            pt.provider_payload #>> '{data,transactionDateTime}',
            pt.provider_payload ->> 'transactionDateTime'
        )), '') AS transaction_datetime
    FROM public.payment_transactions pt
    WHERE pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
), extracted AS (
    SELECT
        r.*,
        CASE
            WHEN r.actual_reference IS NULL THEN 1
            ELSE ROW_NUMBER() OVER (
                PARTITION BY r.actual_reference
                ORDER BY
                    CASE
                        WHEN r.existing_reference = r.actual_reference THEN 0
                        ELSE 1
                    END,
                    r.created_at NULLS LAST,
                    r.payment_transaction_id
            )
        END AS reference_rank
    FROM raw_extracted r
)
UPDATE public.payment_transactions pt
SET
    order_code = CASE
        WHEN e.payload_order_code ~ '^[0-9]{1,18}$'
            THEN e.payload_order_code::BIGINT
        ELSE pt.order_code
    END,
    provider_transaction_id = CASE
        WHEN e.actual_reference IS NULL THEN NULL
        WHEN e.reference_rank = 1 THEN e.actual_reference
        ELSE NULL
    END,
    payment_link_id = COALESCE(
        e.recovered_payment_link_id,
        pt.payment_link_id
    ),
    capture_source = CASE
        WHEN pt.webhook_success IS NOT NULL THEN 'Webhook'
        WHEN pt.provider_payload IS NOT NULL THEN 'Polling'
        ELSE 'Legacy'
    END,
    capture_fingerprint = CASE
        WHEN pt.capture_fingerprint ~ '^[0-9A-Fa-f]{64}$'
            THEN lower(pt.capture_fingerprint)
        ELSE NULL
    END,
    source_account_bank_id = COALESCE(
        e.source_account_bank_id,
        NULLIF(NULLIF(BTRIM(pt.source_account_bank_id), ''), '0')
    ),
    source_account_bank_name = COALESCE(
        e.source_account_bank_name,
        NULLIF(NULLIF(BTRIM(pt.source_account_bank_name), ''), '0')
    ),
    source_account_number = COALESCE(
        e.source_account_number,
        NULLIF(NULLIF(BTRIM(pt.source_account_number), ''), '0')
    ),
    source_account_name = COALESCE(
        e.source_account_name,
        NULLIF(NULLIF(BTRIM(pt.source_account_name), ''), '0')
    ),
    destination_account_number = CASE
        WHEN e.destination_account_number IS NOT NULL
            THEN e.destination_account_number
        WHEN e.destination_virtual_account_number IS NOT NULL
             AND NULLIF(NULLIF(
                 BTRIM(pt.destination_account_number),
                 ''
             ), '0') = e.destination_virtual_account_number
            THEN NULL
        WHEN NULLIF(NULLIF(
                 BTRIM(pt.destination_account_number),
                 ''
             ), '0') ~* '^V'
            THEN NULL
        ELSE NULLIF(NULLIF(
            BTRIM(pt.destination_account_number),
            ''
        ), '0')
    END,
    destination_account_name = CASE
        WHEN e.destination_account_name IS NOT NULL
            THEN e.destination_account_name
        WHEN e.destination_virtual_account_name IS NOT NULL
             AND NULLIF(NULLIF(
                 BTRIM(pt.destination_account_name),
                 ''
             ), '0') = e.destination_virtual_account_name
            THEN NULL
        WHEN NULLIF(NULLIF(
                 BTRIM(pt.destination_account_number),
                 ''
             ), '0') ~* '^V'
            THEN NULL
        ELSE NULLIF(NULLIF(
            BTRIM(pt.destination_account_name),
            ''
        ), '0')
    END,
    destination_virtual_account_number = COALESCE(
        e.destination_virtual_account_number,
        NULLIF(NULLIF(
            BTRIM(pt.destination_virtual_account_number),
            ''
        ), '0'),
        CASE
            WHEN NULLIF(NULLIF(
                     BTRIM(pt.destination_account_number),
                     ''
                 ), '0') ~* '^V'
                THEN NULLIF(NULLIF(
                    BTRIM(pt.destination_account_number),
                    ''
                ), '0')
        END
    ),
    destination_virtual_account_name = COALESCE(
        e.destination_virtual_account_name,
        NULLIF(NULLIF(
            BTRIM(pt.destination_virtual_account_name),
            ''
        ), '0'),
        CASE
            WHEN NULLIF(NULLIF(
                     BTRIM(pt.destination_account_number),
                     ''
                 ), '0') ~* '^V'
                THEN NULLIF(NULLIF(
                    BTRIM(pt.destination_account_name),
                    ''
                ), '0')
        END
    ),
    paid_at = CASE
        WHEN e.transaction_datetime ~
            '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?(Z|[+-][0-9]{2}:?[0-9]{2})$'
             AND pg_input_is_valid(
                 e.transaction_datetime,
                 'timestamp with time zone'
             )
            THEN e.transaction_datetime::TIMESTAMPTZ
                AT TIME ZONE 'UTC'
        WHEN e.transaction_datetime ~
            '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}([.][0-9]{1,6})?$'
             AND pg_input_is_valid(
                 replace(e.transaction_datetime, 'T', ' '),
                 'timestamp without time zone'
             )
            THEN (
                replace(e.transaction_datetime, 'T', ' ')::TIMESTAMP
                AT TIME ZONE 'Asia/Ho_Chi_Minh'
            ) AT TIME ZONE 'UTC'
        ELSE pt.paid_at
    END
FROM extracted e
WHERE e.payment_transaction_id = pt.payment_transaction_id;

-- Attach each booking transaction to exactly one best request candidate.
WITH request_candidates AS (
    SELECT
        pt.payment_transaction_id,
        pr.payment_request_id,
        ROW_NUMBER() OVER (
            PARTITION BY pt.payment_transaction_id
            ORDER BY
                CASE
                    WHEN pt.purpose = 'BookingDeposit'
                         AND pr.phase = 'deposit' THEN 0
                    WHEN pt.purpose = 'BookingRemaining'
                         AND pr.phase = 'remaining' THEN 0
                    ELSE 1
                END,
                CASE
                    WHEN pt.payment_link_id IS NOT NULL
                         AND pr.payment_link_id = pt.payment_link_id
                        THEN 0
                    ELSE 1
                END,
                CASE
                    WHEN pt.order_code IS NOT NULL
                         AND pr.order_code = pt.order_code
                        THEN 0
                    ELSE 1
                END,
                pr.created_at DESC,
                pr.payment_request_id DESC
        ) AS candidate_rank
    FROM public.payment_transactions pt
    JOIN public.payment_requests pr
      ON pr.provider = 'PayOS'
     AND pr.booking_id = pt.booking_id
     AND (
         (pt.purpose = 'BookingDeposit'
          AND pr.phase IN ('deposit', 'legacy_unknown'))
         OR
         (pt.purpose = 'BookingRemaining'
          AND pr.phase IN ('remaining', 'legacy_unknown'))
     )
     AND (
         (
             pt.payment_link_id IS NOT NULL
             AND pr.payment_link_id = pt.payment_link_id
         )
         OR (
             pt.order_code IS NOT NULL
             AND pr.order_code = pt.order_code
         )
     )
    WHERE pt.payment_request_id IS NULL
      AND pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
      AND pt.purpose IN ('BookingDeposit', 'BookingRemaining')
)
UPDATE public.payment_transactions pt
SET payment_request_id = candidate.payment_request_id,
    destination_account_bank_bin = COALESCE(
        pt.destination_account_bank_bin,
        pr.destination_bank_bin
    ),
    destination_account_bank_name = COALESCE(
        pt.destination_account_bank_name,
        pr.destination_bank_name
    )
FROM request_candidates candidate
JOIN public.payment_requests pr
  ON pr.payment_request_id = candidate.payment_request_id
WHERE candidate.candidate_rank = 1
  AND pt.payment_transaction_id = candidate.payment_transaction_id;

-- Reconcile by the aggregate received amount. Every distinct real transaction
-- remains in the ledger and contributes to its payment request.
WITH request_totals AS (
    SELECT
        pt.payment_request_id,
        pr.amount AS expected_amount,
        SUM(pt.amount) AS observed_total
    FROM public.payment_transactions pt
    JOIN public.payment_requests pr
      ON pr.payment_request_id = pt.payment_request_id
     AND pr.provider = 'PayOS'
    WHERE pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
      AND pr.legacy_reconciliation_version IS DISTINCT FROM 'V20260716'
    GROUP BY pt.payment_request_id, pr.amount
)
UPDATE public.payment_transactions pt
SET reconciliation_status = CASE
    WHEN totals.expected_amount IS NULL THEN 'Unexpected'
    WHEN totals.observed_total < totals.expected_amount THEN 'Partial'
    WHEN totals.observed_total > totals.expected_amount THEN 'AmountMismatch'
    ELSE 'Matched'
END
FROM request_totals totals
WHERE totals.payment_request_id = pt.payment_request_id
  AND pt.channel = 'PayOS'
  AND pt.legacy_reconciliation_version = 'V20260716';

UPDATE public.payment_transactions
SET reconciliation_status = 'Orphan'
WHERE channel = 'PayOS'
  AND legacy_reconciliation_version = 'V20260716'
  AND purpose IN ('BookingDeposit', 'BookingRemaining')
  AND payment_request_id IS NULL;

-- Preserve the one-active-request-per-booking-phase invariant. Prefer the link
-- still cached on the booking, then the newest request. Historical exact-paid
-- requests remain PAID; older incomplete requests become SUPERSEDED.
WITH ranked_requests AS (
    SELECT
        pr.payment_request_id,
        ROW_NUMBER() OVER (
            PARTITION BY pr.booking_id, pr.phase
            ORDER BY
                CASE
                    WHEN b.payment_code IS NOT NULL
                         AND pr.payment_link_id = b.payment_code
                        THEN 0
                    ELSE 1
                END,
                pr.created_at DESC,
                pr.payment_request_id DESC
        ) AS active_rank
    FROM public.payment_requests pr
    JOIN public.bookings b ON b.booking_id = pr.booking_id
    WHERE pr.provider = 'PayOS'
      AND pr.provider_payload ->> '_source' IN (
          'legacy_payment_transaction',
          'bookings_legacy_cache'
      )
      AND pr.legacy_reconciliation_version IS DISTINCT FROM 'V20260716'
      AND pr.phase IN ('deposit', 'remaining')
)
UPDATE public.payment_requests pr
SET status = 'SUPERSEDED',
    updated_at = CURRENT_TIMESTAMP
FROM ranked_requests ranked
WHERE ranked.payment_request_id = pr.payment_request_id
  AND ranked.active_rank > 1
  AND pr.status IN (
      'PENDING',
      'PROCESSING',
      'REQUIRES_REVIEW',
      'UNKNOWN'
  );

-- Keep request status aligned with the aggregate evidence. A legacy booking
-- timestamp by itself is not proof that the transaction ledger is complete.
WITH request_evidence AS (
    SELECT
        pr.payment_request_id,
        pr.booking_id,
        pr.phase,
        pr.payment_link_id,
        pr.amount AS expected_amount,
        pr.status AS current_status,
        COUNT(pt.payment_transaction_id) AS transaction_count,
        COALESCE(SUM(pt.amount), 0) AS observed_total
    FROM public.payment_requests pr
    LEFT JOIN public.payment_transactions pt
      ON pt.payment_request_id = pr.payment_request_id
     AND pt.channel = 'PayOS'
     AND pt.legacy_reconciliation_version = 'V20260716'
    WHERE pr.provider = 'PayOS'
      AND pr.provider_payload ->> '_source' IN (
          'legacy_payment_transaction',
          'bookings_legacy_cache'
      )
      AND pr.legacy_reconciliation_version IS DISTINCT FROM 'V20260716'
    GROUP BY
        pr.payment_request_id,
        pr.booking_id,
        pr.phase,
        pr.payment_link_id,
        pr.amount,
        pr.status
), ranked_evidence AS (
    SELECT
        evidence.*,
        ROW_NUMBER() OVER (
            PARTITION BY evidence.booking_id, evidence.phase
            ORDER BY
                CASE
                    WHEN b.payment_code IS NOT NULL
                         AND evidence.payment_link_id = b.payment_code
                        THEN 0
                    ELSE 1
                END,
                pr.created_at DESC,
                evidence.payment_request_id DESC
        ) AS active_rank
    FROM request_evidence evidence
    JOIN public.payment_requests pr
      ON pr.payment_request_id = evidence.payment_request_id
    JOIN public.bookings b ON b.booking_id = evidence.booking_id
), desired_request_status AS (
    SELECT
        evidence.payment_request_id,
        CASE
            WHEN evidence.transaction_count > 0
                 AND evidence.expected_amount IS NOT NULL
                 AND evidence.observed_total = evidence.expected_amount
                THEN 'PAID'
            WHEN evidence.transaction_count > 0
                 AND evidence.active_rank > 1
                THEN 'SUPERSEDED'
            WHEN evidence.transaction_count > 0
                 AND evidence.expected_amount IS NULL
                THEN 'REQUIRES_REVIEW'
            WHEN evidence.transaction_count > 0
                 AND evidence.observed_total < evidence.expected_amount
                THEN 'PROCESSING'
            WHEN evidence.transaction_count > 0
                 AND evidence.observed_total > evidence.expected_amount
                THEN 'REQUIRES_REVIEW'
            WHEN evidence.current_status = 'PAID'
                 AND evidence.active_rank = 1
                THEN 'REQUIRES_REVIEW'
            WHEN evidence.current_status = 'PAID'
                THEN 'SUPERSEDED'
            ELSE evidence.current_status
        END AS desired_status
    FROM ranked_evidence evidence
)
UPDATE public.payment_requests pr
SET status = desired.desired_status,
    updated_at = CURRENT_TIMESTAMP
FROM desired_request_status desired
WHERE desired.payment_request_id = pr.payment_request_id
  AND pr.status IS DISTINCT FROM desired.desired_status;

-- Mark one-time legacy reconciliation ownership in a dedicated column. Provider
-- payload is intentionally replaceable runtime evidence and cannot safely own
-- migration bookkeeping.
UPDATE public.payment_requests
SET legacy_reconciliation_version = 'V20260716'
WHERE provider = 'PayOS'
  AND provider_payload ->> '_source' IN (
      'legacy_payment_transaction',
      'bookings_legacy_cache'
  )
  AND legacy_reconciliation_version IS DISTINCT FROM 'V20260716';

-- Preserve only runtime-compatible SHA-256 fingerprints and deterministically
-- clear any duplicate before enforcing uniqueness.
WITH ranked_fingerprints AS (
    SELECT
        payment_transaction_id,
        ROW_NUMBER() OVER (
            PARTITION BY channel, capture_fingerprint
            ORDER BY
                created_at NULLS LAST,
                payment_transaction_id
        ) AS fingerprint_rank
    FROM public.payment_transactions
    WHERE provider_transaction_id IS NULL
      AND capture_fingerprint IS NOT NULL
)
UPDATE public.payment_transactions pt
SET capture_fingerprint = NULL
FROM ranked_fingerprints ranked
WHERE ranked.payment_transaction_id = pt.payment_transaction_id
  AND ranked.fingerprint_rank > 1;

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_transactions_channel_capture_fingerprint
    ON public.payment_transactions(channel, capture_fingerprint)
    WHERE provider_transaction_id IS NULL
      AND capture_fingerprint IS NOT NULL;

-- Aggregate anomalies produce one alert per payment request, not one alert per
-- contributing split transfer.
WITH request_alert_evidence AS (
    SELECT
        pt.payment_request_id,
        CASE
            WHEN BOOL_OR(
                pt.reconciliation_status = 'AmountMismatch'
            ) THEN 'AmountMismatch'
            ELSE 'Unexpected'
        END AS reconciliation_status,
        MIN(pt.payment_transaction_id) AS representative_transaction_id,
        MIN(pt.booking_id) AS booking_id,
        MIN(pt.order_code) AS order_code,
        MIN(pt.payment_link_id) AS payment_link_id,
        SUM(pt.amount) AS observed_total,
        pr.amount AS expected_amount
    FROM public.payment_transactions pt
    JOIN public.payment_requests pr
      ON pr.payment_request_id = pt.payment_request_id
    WHERE pt.channel = 'PayOS'
      AND pt.legacy_reconciliation_version = 'V20260716'
      AND pt.reconciliation_status IN (
          'AmountMismatch',
          'Unexpected'
      )
    GROUP BY
        pt.payment_request_id,
        pr.amount
)
INSERT INTO public.system_alerts (
    type,
    severity,
    message,
    metadata,
    resolved,
    created_at
)
SELECT
    CASE evidence.reconciliation_status
        WHEN 'AmountMismatch' THEN 'PayOSAmountMismatch'
        ELSE 'PayOSUnexpectedTransaction'
    END,
    'High',
    CASE evidence.reconciliation_status
        WHEN 'AmountMismatch' THEN 'Legacy PayOS transactions exceed the expected payment request amount.'
        ELSE 'Legacy PayOS transaction has no reliable expected payment request amount.'
    END,
    jsonb_build_object(
        'paymentTransactionId',
            evidence.representative_transaction_id,
        'paymentRequestId', evidence.payment_request_id,
        'bookingId', evidence.booking_id,
        'orderCode', evidence.order_code,
        'paymentLinkId', evidence.payment_link_id,
        'observedTotal', evidence.observed_total,
        'expectedAmount', evidence.expected_amount
    ),
    FALSE,
    CURRENT_TIMESTAMP
FROM request_alert_evidence evidence
WHERE NOT EXISTS (
    SELECT 1
    FROM public.system_alerts sa
    WHERE sa.type = CASE evidence.reconciliation_status
        WHEN 'AmountMismatch' THEN 'PayOSAmountMismatch'
        ELSE 'PayOSUnexpectedTransaction'
    END
      AND sa.metadata ->> 'paymentRequestId'
          = evidence.payment_request_id::TEXT
);

-- A transaction with no trustworthy request remains independently actionable.
INSERT INTO public.system_alerts (
    type,
    severity,
    message,
    metadata,
    resolved,
    created_at
)
SELECT
    'PayOSOrphanTransaction',
    'High',
    'Legacy PayOS transaction could not be linked to a payment request.',
    jsonb_build_object(
        'paymentTransactionId', pt.payment_transaction_id,
        'bookingId', pt.booking_id,
        'orderCode', pt.order_code,
        'paymentLinkId', pt.payment_link_id,
        'reference', pt.provider_transaction_id,
        'amount', pt.amount
    ),
    FALSE,  
    CURRENT_TIMESTAMP
FROM public.payment_transactions pt
WHERE pt.channel = 'PayOS'
  AND pt.legacy_reconciliation_version = 'V20260716'
  AND pt.reconciliation_status = 'Orphan'
  AND NOT EXISTS (
      SELECT 1
      FROM public.system_alerts sa
      WHERE sa.type = 'PayOSOrphanTransaction'
        AND sa.metadata ->> 'paymentTransactionId'
            = pt.payment_transaction_id::TEXT
  );

COMMENT ON TABLE public.payment_requests IS
    'PayOS payment-link requests. Actual money movements are stored in payment_transactions.';
COMMENT ON COLUMN public.payment_requests.display_account_number IS
    'Account shown to the payer on the payment link; it may be a virtual account.';
COMMENT ON COLUMN public.payment_transactions.destination_account_number IS
    'Actual destination accountNumber reported for the bank transaction.';
COMMENT ON COLUMN public.payment_transactions.destination_virtual_account_number IS
    'Virtual destination account reported separately by the provider.';
COMMENT ON COLUMN public.payment_transactions.provider_payload IS
    'Polling/provider transaction evidence; never overwritten by a later webhook.';
COMMENT ON COLUMN public.payment_transactions.webhook_payload IS
    'Exact raw signed webhook body when captured by the new webhook path; NULL for legacy rows.';
COMMENT ON COLUMN public.payment_transactions.legacy_reconciliation_version IS
    'Durable marker for rows owned by the one-time V20260716 legacy reconciliation snapshot.';

COMMIT;
