-- =====================================================
-- Migration: normalize current bank accounts and add real-money payment transactions
-- Date: 2026-07-15
--
-- Purpose:
--   1. Move the current user bank account out of tutor_profiles into bank_accounts.
--   2. Keep withdrawal_requests bank columns as historical payout snapshots.
--   3. Add payment_transactions for successful PayOS/manual real-money movements.
-- =====================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.bank_accounts (
    bank_account_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             VARCHAR(50) NOT NULL,
    bank_name           VARCHAR(100),
    account_number      VARCHAR(50),
    account_holder_name VARCHAR(100),
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bank_accounts_userid_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS bank_accounts_userid_key
    ON public.bank_accounts(user_id);

INSERT INTO public.bank_accounts (
    user_id,
    bank_name,
    account_number,
    account_holder_name,
    created_at,
    updated_at
)
SELECT
    tp.tutor_id,
    tp.bank_name,
    tp.bank_account_number,
    tp.bank_account_name,
    COALESCE(tp.bank_changed_at, tp.updated_at, tp.created_at, CURRENT_TIMESTAMP),
    COALESCE(tp.bank_changed_at, tp.updated_at, CURRENT_TIMESTAMP)
FROM public.tutor_profiles tp
WHERE tp.bank_name IS NOT NULL
   OR tp.bank_account_number IS NOT NULL
   OR tp.bank_account_name IS NOT NULL
ON CONFLICT (user_id) DO UPDATE SET
    bank_name = EXCLUDED.bank_name,
    account_number = EXCLUDED.account_number,
    account_holder_name = EXCLUDED.account_holder_name,
    updated_at = EXCLUDED.updated_at;

ALTER TABLE public.tutor_profiles
    DROP COLUMN IF EXISTS bank_name,
    DROP COLUMN IF EXISTS bank_account_number,
    DROP COLUMN IF EXISTS bank_account_name,
    DROP COLUMN IF EXISTS bank_changed_at;

COMMENT ON TABLE public.bank_accounts IS 'Current bank account per user. Historical payout snapshots stay on withdrawal_requests.';

COMMIT;

BEGIN;

CREATE TABLE IF NOT EXISTS public.payment_transactions (
    payment_transaction_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                      VARCHAR(50),
    channel                      VARCHAR(20) NOT NULL,
    direction                    VARCHAR(20) NOT NULL,
    purpose                      VARCHAR(50) NOT NULL,
    status                       VARCHAR(20) NOT NULL DEFAULT 'Succeeded',
    amount                       NUMERIC(15, 2) NOT NULL,
    currency                     VARCHAR(10) NOT NULL DEFAULT 'VND',
    order_code                   BIGINT,
    provider_transaction_id      TEXT,
    payment_link_id              VARCHAR(255),
    booking_id                   INTEGER,
    topup_request_id             INTEGER,
    withdrawal_id                INTEGER,
    description                  TEXT,
    paid_at                      TIMESTAMP WITHOUT TIME ZONE,
    created_at                   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_by                 VARCHAR(50),
    note                         TEXT,
    webhook_code                 VARCHAR(50),
    webhook_desc                 TEXT,
    webhook_success              BOOLEAN,
    provider_code                VARCHAR(50),
    provider_desc                TEXT,
    source_account_bank_id       VARCHAR(50),
    source_account_bank_name     VARCHAR(100),
    source_account_number        VARCHAR(50),
    source_account_name          VARCHAR(200),
    destination_account_bank_id  VARCHAR(50),
    destination_account_bank_name VARCHAR(100),
    destination_account_number   VARCHAR(50),
    destination_account_name     VARCHAR(200),
    provider_payload             JSONB,
    CONSTRAINT payment_transactions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(user_id) ON DELETE SET NULL,
    CONSTRAINT payment_transactions_processed_by_fkey FOREIGN KEY (processed_by)
        REFERENCES public.users(user_id) ON DELETE SET NULL,
    CONSTRAINT payment_transactions_booking_id_fkey FOREIGN KEY (booking_id)
        REFERENCES public.bookings(booking_id) ON DELETE SET NULL,
    CONSTRAINT payment_transactions_topup_request_id_fkey FOREIGN KEY (topup_request_id)
        REFERENCES public.topup_requests(topup_request_id) ON DELETE SET NULL,
    CONSTRAINT payment_transactions_withdrawal_id_fkey FOREIGN KEY (withdrawal_id)
        REFERENCES public.withdrawal_requests(withdrawal_id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_transactions_channel_provider_transaction_id
    ON public.payment_transactions(channel, provider_transaction_id)
    WHERE provider_transaction_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_transactions_user_id
    ON public.payment_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_order_code
    ON public.payment_transactions(order_code);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_booking_id
    ON public.payment_transactions(booking_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_topup_request_id
    ON public.payment_transactions(topup_request_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_withdrawal_id
    ON public.payment_transactions(withdrawal_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_paid_at
    ON public.payment_transactions(paid_at);

COMMENT ON TABLE public.payment_transactions IS 'Successful real-money transactions from PayOS webhooks and manual bank-transfer confirmations.';
COMMENT ON COLUMN public.payment_transactions.provider_payload IS 'Raw provider payload for PayOS webhook audit; null for manual flows.';

COMMIT;
