BEGIN;

-- Refactor schema for Tutor Setup + Parent Booking flow.
-- PostgreSQL 17 compatible, idempotent where possible, and intentionally does not migrate old data.

ALTER TABLE public.users
    RENAME COLUMN IF EXISTS isdeleted TO isdeactivated;

ALTER TABLE public.users
    RENAME COLUMN IF EXISTS deletedat TO deactivatedat;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS isdeactivated boolean DEFAULT false;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS deactivatedat timestamp without time zone;

CREATE TABLE IF NOT EXISTS public.gradelevels (
    gradelevelid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gradename character varying(100) NOT NULL,
    levelorder integer NOT NULL,
    createdat timestamp without time zone DEFAULT now()
);

ALTER TABLE public.gradelevels
    ADD COLUMN IF NOT EXISTS createdat timestamp without time zone DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_gradelevels_levelorder'
          AND conrelid = 'public.gradelevels'::regclass
    ) THEN
        ALTER TABLE public.gradelevels
            ADD CONSTRAINT uq_gradelevels_levelorder UNIQUE (levelorder);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_gradelevels_gradename'
          AND conrelid = 'public.gradelevels'::regclass
    ) THEN
        ALTER TABLE public.gradelevels
            ADD CONSTRAINT uq_gradelevels_gradename UNIQUE (gradename);
    END IF;
END
$$;

INSERT INTO public.gradelevels (gradename, levelorder)
VALUES
    ('Lớp 1', 1),
    ('Lớp 2', 2),
    ('Lớp 3', 3),
    ('Lớp 4', 4),
    ('Lớp 5', 5),
    ('Lớp 6', 6),
    ('Lớp 7', 7),
    ('Lớp 8', 8),
    ('Lớp 9', 9),
    ('Lớp 10', 10),
    ('Lớp 11', 11),
    ('Lớp 12', 12)
ON CONFLICT (levelorder) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.tutorsubjectgradeprices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutorid character varying(50) NOT NULL,
    subjectid integer NOT NULL,
    gradelevelid integer NOT NULL,
    priceperhour numeric(12,2) NOT NULL,
    currency character varying(10) NOT NULL DEFAULT 'VND',
    isactive boolean NOT NULL DEFAULT true,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_tutorsubjectgradeprices_tutor_subject_grade'
          AND conrelid = 'public.tutorsubjectgradeprices'::regclass
    ) THEN
        ALTER TABLE public.tutorsubjectgradeprices
            ADD CONSTRAINT uq_tutorsubjectgradeprices_tutor_subject_grade
            UNIQUE (tutorid, subjectid, gradelevelid);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutorsubjectgradeprices_priceperhour_nonnegative'
          AND conrelid = 'public.tutorsubjectgradeprices'::regclass
    ) THEN
        ALTER TABLE public.tutorsubjectgradeprices
            ADD CONSTRAINT ck_tutorsubjectgradeprices_priceperhour_nonnegative
            CHECK (priceperhour >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tutorsubjectgradeprices_tutor'
          AND conrelid = 'public.tutorsubjectgradeprices'::regclass
    ) THEN
        ALTER TABLE public.tutorsubjectgradeprices
            ADD CONSTRAINT fk_tutorsubjectgradeprices_tutor
            FOREIGN KEY (tutorid) REFERENCES public.tutorprofiles(tutorid) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tutorsubjectgradeprices_subject'
          AND conrelid = 'public.tutorsubjectgradeprices'::regclass
    ) THEN
        ALTER TABLE public.tutorsubjectgradeprices
            ADD CONSTRAINT fk_tutorsubjectgradeprices_subject
            FOREIGN KEY (subjectid) REFERENCES public.subjects(subjectid) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tutorsubjectgradeprices_gradelevel'
          AND conrelid = 'public.tutorsubjectgradeprices'::regclass
    ) THEN
        ALTER TABLE public.tutorsubjectgradeprices
            ADD CONSTRAINT fk_tutorsubjectgradeprices_gradelevel
            FOREIGN KEY (gradelevelid) REFERENCES public.gradelevels(gradelevelid);
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('public.tutorcombos') IS NOT NULL
       AND to_regclass('public.tutorpackages') IS NULL THEN
        ALTER TABLE public.tutorcombos RENAME TO tutorpackages;
    END IF;

    IF to_regclass('public.tutorcombofixedslots') IS NOT NULL
       AND to_regclass('public.tutorpackagefixedslots') IS NULL THEN
        ALTER TABLE public.tutorcombofixedslots RENAME TO tutorpackagefixedslots;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.tutorpackages (
    packageid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutorid character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    packagetype integer NOT NULL,
    durationminutespersession integer NOT NULL,
    description text,
    isactive boolean NOT NULL DEFAULT true,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorpackages'
          AND column_name = 'comboid'
    ) THEN
        ALTER TABLE public.tutorpackages RENAME COLUMN comboid TO packageid;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorpackages'
          AND column_name = 'combotype'
    ) THEN
        ALTER TABLE public.tutorpackages RENAME COLUMN combotype TO packagetype;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorpackages'
          AND column_name = 'packagetype'
          AND data_type <> 'integer'
    ) THEN
        ALTER TABLE public.tutorpackages
            ALTER COLUMN packagetype TYPE integer
            USING CASE
                WHEN lower(packagetype::text) = 'flexible' THEN 1
                WHEN lower(packagetype::text) = 'fixed' THEN 2
                ELSE packagetype::integer
            END;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorpackages'
          AND column_name = 'totalsessions'
    ) THEN
        ALTER TABLE public.tutorpackages DROP COLUMN totalsessions;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tutorpackages_tutor'
          AND conrelid = 'public.tutorpackages'::regclass
    ) THEN
        ALTER TABLE public.tutorpackages
            ADD CONSTRAINT fk_tutorpackages_tutor
            FOREIGN KEY (tutorid) REFERENCES public.tutorprofiles(tutorid) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutorpackages_packagetype'
          AND conrelid = 'public.tutorpackages'::regclass
    ) THEN
        ALTER TABLE public.tutorpackages
            ADD CONSTRAINT ck_tutorpackages_packagetype
            CHECK (packagetype IN (1, 2));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutorpackages_duration_positive'
          AND conrelid = 'public.tutorpackages'::regclass
    ) THEN
        ALTER TABLE public.tutorpackages
            ADD CONSTRAINT ck_tutorpackages_duration_positive
            CHECK (durationminutespersession > 0);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.tutorpackagefixedslots (
    fixedslotid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packageid integer NOT NULL,
    dayofweek integer NOT NULL,
    starttime time without time zone NOT NULL,
    endtime time without time zone NOT NULL,
    createdat timestamp without time zone DEFAULT now()
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorpackagefixedslots'
          AND column_name = 'comboid'
    ) THEN
        ALTER TABLE public.tutorpackagefixedslots RENAME COLUMN comboid TO packageid;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tutorpackagefixedslots_package'
          AND conrelid = 'public.tutorpackagefixedslots'::regclass
    ) THEN
        ALTER TABLE public.tutorpackagefixedslots
            ADD CONSTRAINT fk_tutorpackagefixedslots_package
            FOREIGN KEY (packageid) REFERENCES public.tutorpackages(packageid) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutorpackagefixedslots_dayofweek'
          AND conrelid = 'public.tutorpackagefixedslots'::regclass
    ) THEN
        ALTER TABLE public.tutorpackagefixedslots
            ADD CONSTRAINT ck_tutorpackagefixedslots_dayofweek
            CHECK (dayofweek BETWEEN 1 AND 7);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutorpackagefixedslots_time_range'
          AND conrelid = 'public.tutorpackagefixedslots'::regclass
    ) THEN
        ALTER TABLE public.tutorpackagefixedslots
            ADD CONSTRAINT ck_tutorpackagefixedslots_time_range
            CHECK (starttime < endtime);
    END IF;
END
$$;

ALTER TABLE public.studentprofiles
    ADD COLUMN IF NOT EXISTS gradelevelid integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_studentprofiles_gradelevel'
          AND conrelid = 'public.studentprofiles'::regclass
    ) THEN
        ALTER TABLE public.studentprofiles
            ADD CONSTRAINT fk_studentprofiles_gradelevel
            FOREIGN KEY (gradelevelid) REFERENCES public.gradelevels(gradelevelid);
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'studentprofiles'
          AND column_name = 'gradelevel'
    ) THEN
        BEGIN
            ALTER TABLE public.studentprofiles DROP COLUMN gradelevel;
        EXCEPTION
            WHEN dependent_objects_still_exist THEN
                RAISE NOTICE 'TODO: public.studentprofiles.gradelevel could not be dropped because dependencies still exist. Treat as deprecated.';
            WHEN undefined_column THEN
                NULL;
        END;
    END IF;
END
$$;

ALTER TABLE public.tutoravailability
    ADD COLUMN IF NOT EXISTS isactive boolean NOT NULL DEFAULT true;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutoravailability_dayofweek'
          AND conrelid = 'public.tutoravailability'::regclass
    ) THEN
        ALTER TABLE public.tutoravailability
            ADD CONSTRAINT ck_tutoravailability_dayofweek
            CHECK (dayofweek BETWEEN 1 AND 7);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_tutoravailability_time_range'
          AND conrelid = 'public.tutoravailability'::regclass
    ) THEN
        ALTER TABLE public.tutoravailability
            ADD CONSTRAINT ck_tutoravailability_time_range
            CHECK (starttime < endtime);
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorprofiles'
          AND column_name = 'hourlyrate'
    ) THEN
        BEGIN
            ALTER TABLE public.tutorprofiles DROP COLUMN hourlyrate;
        EXCEPTION
            WHEN dependent_objects_still_exist THEN
                RAISE NOTICE 'TODO: public.tutorprofiles.hourlyrate could not be dropped because dependencies still exist. Treat as deprecated.';
            WHEN undefined_column THEN
                NULL;
        END;
    END IF;
END
$$;

ALTER TABLE public.bookings
    ADD COLUMN IF NOT EXISTS tutorsubjectgradepriceid integer,
    ADD COLUMN IF NOT EXISTS packageid integer,
    ADD COLUMN IF NOT EXISTS totalsessions integer,
    ADD COLUMN IF NOT EXISTS durationminutespersession integer,
    ADD COLUMN IF NOT EXISTS priceperhour numeric(12,2),
    ADD COLUMN IF NOT EXISTS totalamount numeric(12,2),
    ADD COLUMN IF NOT EXISTS currency character varying(10) DEFAULT 'VND';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'bookings'
          AND column_name = 'comboid'
    ) THEN
        ALTER TABLE public.bookings RENAME COLUMN comboid TO packageid;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_bookings_tutorsubjectgradeprice'
          AND conrelid = 'public.bookings'::regclass
    ) THEN
        ALTER TABLE public.bookings
            ADD CONSTRAINT fk_bookings_tutorsubjectgradeprice
            FOREIGN KEY (tutorsubjectgradepriceid)
            REFERENCES public.tutorsubjectgradeprices(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_bookings_package'
          AND conrelid = 'public.bookings'::regclass
    ) THEN
        ALTER TABLE public.bookings
            ADD CONSTRAINT fk_bookings_package
            FOREIGN KEY (packageid)
            REFERENCES public.tutorpackages(packageid);
    END IF;
END
$$;

DO $$
DECLARE
    col_name text;
BEGIN
    FOREACH col_name IN ARRAY ARRAY['subjectid', 'packagetype', 'sessioncount', 'price', 'schedule', 'teachingmode']
    LOOP
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'bookings'
              AND column_name = col_name
        ) THEN
            BEGIN
                EXECUTE format('ALTER TABLE public.bookings DROP COLUMN %I', col_name);
            EXCEPTION
                WHEN dependent_objects_still_exist THEN
                    RAISE NOTICE 'TODO: public.bookings.% could not be dropped because dependencies still exist. Treat as deprecated.', col_name;
                WHEN undefined_column THEN
                    NULL;
            END;
        END IF;
    END LOOP;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tutorprofiles'
          AND column_name = 'teachingmode'
    ) THEN
        BEGIN
            ALTER TABLE public.tutorprofiles DROP COLUMN teachingmode;
        EXCEPTION
            WHEN dependent_objects_still_exist THEN
                RAISE NOTICE 'TODO: public.tutorprofiles.teachingmode could not be dropped because dependencies still exist. Treat as deprecated.';
            WHEN undefined_column THEN
                NULL;
        END;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'lessons'
          AND column_name = 'originalessonid'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'lessons'
          AND column_name = 'originallessonid'
    ) THEN
        ALTER TABLE public.lessons RENAME COLUMN originalessonid TO originallessonid;
    END IF;
END
$$;

ALTER TABLE public.lessons
    ADD COLUMN IF NOT EXISTS sessionindex integer,
    ADD COLUMN IF NOT EXISTS originallessonid integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_lessons_originallessonid'
          AND conrelid = 'public.lessons'::regclass
    ) THEN
        ALTER TABLE public.lessons
            ADD CONSTRAINT fk_lessons_originallessonid
            FOREIGN KEY (originallessonid)
            REFERENCES public.lessons(lessonid);
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('public.tutorsubjects') IS NOT NULL THEN
        BEGIN
            DROP TABLE public.tutorsubjects;
        EXCEPTION
            WHEN dependent_objects_still_exist THEN
                RAISE NOTICE 'TODO: public.tutorsubjects could not be dropped because dependencies still exist. Treat as deprecated; source of truth is public.tutorsubjectgradeprices.';
            WHEN undefined_table THEN
                NULL;
        END;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_tutorsubjectgradeprices_tutor_subject_grade
    ON public.tutorsubjectgradeprices (tutorid, subjectid, gradelevelid);

CREATE INDEX IF NOT EXISTS idx_tutorsubjectgradeprices_tutor_active
    ON public.tutorsubjectgradeprices (tutorid, isactive);

CREATE INDEX IF NOT EXISTS idx_tutoravailability_tutor_day_time
    ON public.tutoravailability (tutorid, dayofweek, starttime, endtime);

CREATE INDEX IF NOT EXISTS idx_tutorpackages_tutor_active_type
    ON public.tutorpackages (tutorid, isactive, packagetype);

CREATE INDEX IF NOT EXISTS idx_tutorpackagefixedslots_package_day
    ON public.tutorpackagefixedslots (packageid, dayofweek);

CREATE INDEX IF NOT EXISTS idx_bookings_parentid
    ON public.bookings (parentid);

CREATE INDEX IF NOT EXISTS idx_bookings_studentid
    ON public.bookings (studentid);

CREATE INDEX IF NOT EXISTS idx_bookings_tutorid
    ON public.bookings (tutorid);

CREATE INDEX IF NOT EXISTS idx_bookings_packageid
    ON public.bookings (packageid);

CREATE INDEX IF NOT EXISTS idx_bookings_tutorsubjectgradepriceid
    ON public.bookings (tutorsubjectgradepriceid);

CREATE INDEX IF NOT EXISTS idx_lessons_tutor_schedule
    ON public.lessons (tutorid, scheduledstart, scheduledend);

CREATE INDEX IF NOT EXISTS idx_lessons_student_schedule
    ON public.lessons (studentid, scheduledstart, scheduledend);

CREATE INDEX IF NOT EXISTS idx_lessons_bookingid
    ON public.lessons (bookingid);

COMMENT ON TABLE public.gradelevels IS
    'Chuan hoa khoi lop Lop 1-12 cho luong Tutor Setup va Parent Booking.';

COMMENT ON TABLE public.tutorsubjectgradeprices IS
    'Tutor day mon nao, khoi nao, gia bao nhieu. Day la source of truth moi cho subject + grade + pricing.';

COMMENT ON TABLE public.tutorpackages IS
    'Package hoc do tutor tao. packagetype=1 la flexible, packagetype=2 la fixed. Booking moi tham chieu package nay qua bookings.packageid.';

COMMENT ON TABLE public.tutorpackagefixedslots IS
    'Lich co dinh cua package fixed. Package flexible khong co ban ghi trong bang nay.';

COMMENT ON COLUMN public.bookings.tutorsubjectgradepriceid IS
    'Subject + grade + price duoc chon tai thoi diem booking.';

COMMENT ON COLUMN public.bookings.packageid IS
    'Package duoc chon tai thoi diem booking.';

COMMENT ON TABLE public.lessons IS
    'Lessons la lich hoc that cua booking. Moi record trong lessons la mot buoi hoc that.';

/*
Business rules after this refactor:
- tutorprofiles.hourlyrate da bi bo hoac deprecated va khong con la source of truth.
- tutorsubjects da bi bo hoac deprecated va khong con la source of truth.
- bookings.subjectid, packagetype cu, sessioncount, price, schedule, teachingmode da bi bo hoac deprecated.
- tutorsubjectgradeprices la source of truth cho tutor + subject + grade + price.
- Booking moi lay gia tu tutorsubjectgradeprices.priceperhour.
- tutoravailability la lich ranh chung, khong phai lich hoc that.
- tutorpackages la source of truth cho package flexible/fixed.
- Booking moi lay package tu tutorpackages qua bookings.packageid.
- tutorpackagefixedslots chi dung cho package fixed.
- Package flexible khong co fixed slots.
- bookings snapshot totalsessions, durationminutespersession, priceperhour, totalamount, currency tai thoi diem booking.
- lessons la source of truth cho lich hoc that.
- Khong co teachingmode vi mac dinh la online.
- Khong co booking_type trong bookings vi packageid da tham chieu tutorpackages.packagetype.
- Khong co tutor_unavailable_dates trong model nay.
- Khong co booking_sessions vi lessons dong vai tro cac session thuc te.
- Khong tao payments moi; he thong tiep tuc su dung wallets, wallettransactions, topuprequests, withdrawalrequests.
- Package da co booking thi khong sua truc tiep; tao package moi va set package cu isactive = false.
*/

COMMIT;
