<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>443fd196-aa99-46cb-9605-3559a356172a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML.Extensions.AspNet" Version="0.5.0" />
		<PackageReference Include="ClosedXML_Excel" Version="1.0.0" />
		<PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.12" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MV.ApplicationLayer\MV.ApplicationLayer.csproj" />
		<ProjectReference Include="..\MV.InfrastructureLayer\MV.InfrastructureLayer.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="wwwroot\Test.html" />
	</ItemGroup>
</Project>
