using Microsoft.AspNetCore.Http;
using MV.DomainLayer.DTO.RequestModel;
using MV.DomainLayer.DTO.ResponseModel;

namespace MV.ApplicationLayer.ServiceInterfaces
{
    public interface IStudentService
    {
        /// <summary>
        /// All student profiles linked to a parent account.
        /// </summary>
        Task<List<StudentProfileResponse>> GetStudentsByParentIdAsync(string parentId);

        /// <summary>
        /// Single student profile — ownership-checked against the parent.
        /// </summary>
        Task<StudentProfileResponse> GetStudentByIdAsync(string studentId, string parentId);

        /// <summary>
        /// Parent creates a new student account; returns credentials (username + temp password).
        /// </summary>
        Task<StudentCredentialsResponse> CreateStudentAsync(CreateStudentRequest request, string parentId);

        /// <summary>
        /// Upload and replace a student's avatar image.
        /// </summary>
        Task<StudentProfileResponse> UpdateAvatarAsync(string studentId, IFormFile avatarFile, string parentId);

        /// <summary>
        /// Update a student's profile fields (name, grade, etc.).
        /// </summary>
        Task<StudentProfileResponse> UpdateStudentAsync(string studentId, UpdateStudentRequest request, string parentId);

        /// <summary>
        /// Delete a student account (parent only).
        /// </summary>
        Task DeleteStudentAsync(string studentId, string parentId);

        // ── Linking flow 1: parent generates a code the student enters ─────

        /// <summary>
        /// Parent generates a one-time link code that the student enters to link accounts.
        /// </summary>
        Task<StudentProfileResponse> GenerateLinkCodeAsync(string studentId, string parentId);

        /// <summary>
        /// Student submits the link code generated by their parent to complete account linking.
        /// </summary>
        Task<StudentProfileResponse> LinkStudentWithCodeAsync(string code, string studentUserId);

        // ── Linking flow 2: student enters a parent code ───────────────────

        /// <summary>
        /// Parent generates a code that the student can use to link themselves to the parent.
        /// </summary>
        Task<string> GenerateParentCodeAsync(string parentId);

        /// <summary>
        /// Student self-links by entering the parent's code.
        /// </summary>
        Task<StudentProfileResponse> StudentSelfLinkAsync(string parentCode, string studentUserId);

        // ── Credentials ───────────────────────────────────────────────────

        /// <summary>
        /// Parent resets a student's password; returns new temporary credentials.
        /// </summary>
        Task<StudentCredentialsResponse> ResetStudentPasswordAsync(string studentId, string parentId);

        /// <summary>
        /// Student checks whether their account is linked to a parent.
        /// </summary>
        Task<StudentLinkStatusResponse> GetLinkStatusAsync(string studentUserId);

        /// <summary>
        /// Student updates their own profile fields (name, birthdate, school, grade, learning goals).
        /// </summary>
        Task<StudentProfileResponse> UpdateSelfProfileAsync(string studentUserId, UpdateStudentRequest request);

        /// <summary>
        /// Student uploads their own avatar — updates both Studentprofile and linked User record.
        /// </summary>
        Task<StudentProfileResponse> UpdateSelfAvatarAsync(string studentUserId, IFormFile avatarFile);
    }
}
